---
# Source: Chowkidar/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: chowkidar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "Chowkidar-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: chowkidar
data:
  config.yaml: |-
    controllers:
    - type: pods
      watchcriterion: map[identifiers:[resourceExists healthCheckExists] operator:and]
        operator: 
        identifiers:
      actions:
      - name: slack
        params:
          channel: channel-name
          token: your-token
