apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: chowkidar
    group: com.stakater.platform
    version: dev
    provider: stakater
  name: chowkidar
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: chowkidar
    group: com.stakater.platform
    version: dev
    provider: stakater
  name: chowkidar
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: chowkidar
    group: com.stakater.platform
    version: dev
    provider: stakater
  name: chowkidar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chowkidar
subjects:
  - kind: ServiceAccount
    name: chowkidar
    namespace: dev