controllers:
- type: po
  watchcriterion:
    operator: and
    identifiers: 
      - "resourceExists"
      - "healthCheckExists"
  actions:
  - name: slack
    params:
      token: "123"
      channel: "channelName"
