controllers:
- type: pods
  watchcriterion:
    operator: and
    identifiers: 
      - "resourceExists"
      - "healthCheckExists"
  actions:
  - name: slack
    params:
      token: <token>
      channel: <channel-name>
