controllers:
- type: pods
  watchcriterion:
    operator: and
    identifiers: ["resourceExists", "healthCheckExists"]
  actions:
  - name: slack
    params:
      token: xoxb-357207387857-2bTuHVBzg402LiDHWd2NOTaW
      channel: "guard-room"
